# Generated by Django 3.2.8 on 2021-10-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
