# Generated by Django 3.2.8 on 2021-10-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='url_media',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.TextField(blank=True, max_length=40),
        ),
    ]
